name: Future Dimension Force
favicon: null
layout_spectrum: 0.03672062745317817
typography_spectrum: 0.997963264817372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6478349680546671
  lightness: 0.023737565614283085
  saturation: 0.7517299589235336
  rhythmicContrast: 0.2637103183660656
purpose: []
